pipeline {
    agent any
    tools {
        maven "MAVEN"
        jdk "JDK"
    }
    stages {
        stage('compile') {
            steps {
                bat 'mvn -f SpringBootDemoApp/pom.xml clean install'
                bat '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
                echo "Compiled Successfully !!"
            }
        }
        stage('junit') {
            steps {
                echo "JUnit passed Successfully !!"
            }
        }
        stage('quality') {
            steps {
                echo "Quality Checked Successfully !!"
            }
        }
        stage('deploy') {
            steps {
                echo "deployed Successfully !!"
            }
        }
    }
}
